#!/usr/bin/env python3
import re
import sys
trg = ''
pattern = r'\w+\((["\'])([^\'"]+)\1.*\)'

with open(sys.argv[1]) as file:
    for line in file:
        if line.strip().startswith('pdf(') or line.strip().startswith('png('):
            trg = re.search(pattern, line).group(2)
            break

if trg == '':
    sys.stderr.write(f'Error: {sys.argv[1]} has no targets\n')
    sys.exit(1)
else:
    print(trg)
